### PR TITLE
Removed the documentation for the Visual Studio C++ template

### PR DESCRIPTION
**Pull request by rprouse**
As requested in #94, I have removed the documentation for the Visual Studio C++ template.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@LegalizeAdulthood would you sanity-check this, please?

**Comment by LegalizeAdulthood** [comment]
Let's leave in the discussion of [Boost Unit Test Adapter](https://visualstudiogallery.msdn.microsoft.com/5f4ae1bd-b769-410e-8238-fb30beda987f).  Let's mention Boost Unit Test Adapter as a suggested add-on but not required.

They just released Community Edition which is free and allows plug-ins, but I haven't yet prepared a documentation change to reflect this.  gcc/g++ 4.9 has also been released since I wrote these initial instructions and I wanted to do some experimenting with that and update both at the same time.  I am reluctant to mention versions of tools that I haven't yet verified for myself to know what the experience is for others.

**Comment by rprouse** [comment]
I've changed the link to the new Visual Studio Community edition and provided a link to the Boost Test Adapter. This is ready to merge if you are happy with it.

**Comment by LegalizeAdulthood** [comment]
Have you tested the Community Edition with the Boost Unit Test Adapter and exercism?

**Comment by rprouse** [comment]
Yes, I have tested the Boost Unit Test adapter and Community Edition, but only with  my template. It is beta, so I find that sometimes it stops working for no apparent reason. A full rebuild or sometimes restarting Visual Studio gets it working again. It does work most of the time though and when it does, it makes the test cycle much nicer.

**Comment by LegalizeAdulthood** [comment]
Is that information recorded in the docs?  The part about it being beta, stops working, etc.

**Comment by rprouse** [comment]
I just have a two sentence blurb about the adapter,

You can run the tests within Visual Studio by installing the [Boost Unit Test Adapter](https://visualstudiogallery.msdn.microsoft.com/5f4ae1bd-b769-410e-8238-fb30beda987f) extension. It is in beta, but it generally works.

**Comment by LegalizeAdulthood** [comment]
Have you updated this pull request?  When I look at the changes, it just shows deletions.

**Comment by LegalizeAdulthood** [comment]
Can you explain to me what you get with the adapter?  When you run the build, it runs the tests already, so you don't need anything to run the tests, just build the solution.

**Comment by rprouse** [comment]
The adapter allows you to run all or individual tests and debug them from within Visual Studio. It works the same as MSTests or running NUnit tests using the nunit test adapter.

Test Explorer

**Comment by LegalizeAdulthood** [comment]
So what do I get when I'm working on an exercise and I say "Build solution", my code compiles and then the tests are run and the test fails.  Does it show up in the test runner as red?

**Comment by LegalizeAdulthood** [comment]
I changed my mind... let's not merge this until I've had a chance to try out this add-on for myself.  I have too many questions about how it is changing the experience and I just need to try it myself instead of making @rprouse answer all my questions :smile: .

**Comment by rprouse** [comment]
No, if you build and run the tests outside of visual studio, the test window is not updated, it is only updated if you run tests. It is the same difference as running NUnit tests at the command line vs in Visual Studio. It is just an alternative for people that are used to testing in Visual Studio.

**Comment by LegalizeAdulthood** [comment]
Yeah, this isn't .NET and unit testing doesn't work the same way in C++.  So let's put this on hold until I have a chance to try it.

**Comment by LegalizeAdulthood** [comment]
OK, I had a chance to play with this and I am conflicted about whether or not it is an improvement.

The problem with the test runner is that it assumes that the tests are **not** run when you build the code.  It assumes that you'll only run the tests by clicking on the little buttons.  So every time you click the button a dialog appears saying that the build failed and asking you if you want to run the last successful build.  I think this is only going to confuse people more.

Running the tests as part of the build and failing the build when you have failing tests is very, very, very normal.  However, the way this test runner works, it is going to be complaining to you with this extra dialog every single time.  I don't think that is an improvement.  I noticed in your screen shots that you weren't actually running the exercises provided by exercism, but were only running your templates.  Please try it with the real code on exercism.

**Comment by kytrinyx** [comment]
If it requires extra clicks, I'd rather not include it. I'm highly biased towards CLI-only workflows, and I don't want exercism to in any way encourage click-based workflows.

**Comment by rprouse** [comment]
The adapter is just a different way of running the tests and integrates
with the way most people run tests in Visual Studio, but it is a minor
point in the doc, so I will remove it tomorrow. I just landed in England
and need a bit of time to settle in.

I assume you will want this PR squashed?

On 19 December 2014 at 09:51, Katrina Owen notifications@github.com wrote:

> If it requires extra clicks, I'd rather not include it. I'm highly biased
> towards CLI-only workflows, and I don't want exercism to in any way
> encourage click-based workflows.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/exercism/docs/pull/111#issuecomment-67647052.

## 

Rob Prouse

I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by LegalizeAdulthood** [comment]
For people doing C#, using an a tool window like this would be typical.

For people doing C++, the opposite is true.

**Comment by rprouse** [comment]
I have removed the information on the Visual Studio test adapter. The PR has been rebased and squashed.

This should be ready to merge.

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
