### PR TITLE
[WIP] Beginning a new navigation implementation.

### PR DESCRIPTION
**Pull request by johno**
This addresses https://github.com/exercism/exercism.io/issues/1847

---

Firstly, what you're doing here is awesome @kytrinyx.

I'm beginning to implement a different navigation scheme in place of the jQuery sidr plugin. I've created this PR to illustrate where I'm at thus far, and to provide a mechanism for feedback and critique. I will keep this updated along the way.

I've added a grid system to help with the overall site structure (read: yak shave). I've opted for the Bootstrap grid. It isn't exactly my favorite, however, it's primary benefit is the fact that it's familiar to most web devs. Which will provide a better means for contribution in the future, rather than some esoteric framework that might shave 1KB in CSS download size.

To start I've added a breadcrumb on the top lev nav. This allows for the help site to appear to be cohesive with the remainder of the exorcism.io:

fmkfxj7njkext4zp6jlmrtubawgdq0yhnvfq3uk7ho0

The "Exorcism.io" link will now serve as the "Return to Exorcism.io" link that existed in the right nav, while the "Help" link will point to the documentation index.

I intend on adding dropdown links to the right nav for each category, which will then list the available posts. Though, I'm also considering adding a navigation page for each category instead. So, a user would click "Languages" in the top right, and end up at a page with a list of the available documentation that belongs to the Language category. Is there a navigation scheme out of those two options that is preferable?

I also intend on adding the Categories with a pages list to the footer, to provide an area to find other potential documentation pages that could be of help.
### TODO:
- [x] Remove sidr.
- [x] Add grid system.
- [x] Add category dropdowns to the right nav.
- [x] Ensure it's mobile friendly.
- [x] Add navigation to the index body.
- [x] Add navigation elements to the footer.
- [ ] Style full page navigation

Please let me know if I'm heading in the wrong direction, or you have another idea for implementation.

Thanks,

John Otander

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is really great stuff!

> [bootstrap grid is] familiar to most web devs. Which will provide a better means for contribution in the future

An _excellent_ choice. I want to optimize for contributions, and currently some of the choices I made early on are a pretty high barrier to entry both because they're cryptic or arcane, or simply because they're complete hacks. I think choosing something that most devs are familiar with is the way to go in an open source project like this.

I think the breadcrumb is what was missing in terms of context. People mentioned that they were surprised to find themselves in a completely different app. I made the choice to make it separate for a number of reasons. First: these things do not change at the same rate or the same reasons as the main website or the problems, so it makes sense for them to live separately. Second, it's much easier to understand a small repository that does one thing than a large one that does many things—which is good for contributions. Third, heroku has a help/docs site that is completely separate from their main site, so I figured if they can do it, so can I :)

> Is there a navigation scheme out of those two options that is preferable?

I really like the idea that languages can have lots of different bits of documentation relevant to them, so after thinking this through a bit, the landing page per category is my favorite.

I also really like the idea of the footer being useful.

This is amazing, I'm so excited!

**Comment by johno** [comment]
> I think the breadcrumb is what was missing in terms of context. People mentioned that they were surprised to find themselves in a completely different app.

That's what I was thinking. This new concept will be "separate", but will ideally feel like it's still part of the same context.

> I made the choice to make it separate for a number of reasons.

The perfect decision IMO :beers: . With a few added links back and forth, the separation won't be noticed by the end user while still providing an ecosystem that's much easier on the contributor. Yay. :confetti_ball: :confetti_ball: 

> I really like the idea that languages can have lots of different bits of documentation relevant to them, so after thinking this through a bit, the landing page per category is my favorite.

That's great. I'm thinking this will make the most sense, and be more adaptive, especially as the amount of content expands.

Stay tuned for more soon.

**Comment by johno** [comment]
Implemented the right nav, and ensured it's mobile friendly. It's a left nav under the site breadcrumb, and then floats right on larger viewports.

**Large viewports:**

jot8da3hfr_uakpl7yjiattg96jgdebsjzhv36y36eo

**Small viewports:**

kj3q8zwg-bw2upahbfofp5tz5jfhz_zvfot5bcyvoyu

**Comment by kytrinyx** [comment]
I really love where this is going!

**Comment by kytrinyx** [comment]
Just checking in!

Is there any chance that the work already done can be merged in? (It seems like anything would be better than what is already there), then other people might be able to jump in and help out with details.

**Comment by johno** [comment]
Sorry about dropping off there for a bit. Work and life get in the way sometimes.

Where I'm currently at can't easily be merged in because the page-based navigation still isn't implemented. Though, perhaps you could help me with that, or point me in the right direction. Currently I can't seem to access the `site.categories` list that's in the `wrapper.us`:

``` liquid
<% site.categories.forEach(function(category){ %>
  <a class="toc_title"><%- category.title %></a>
  <ul class="toc_section">
     <% category.pages.forEach(function(page){ %>
       <li>- <a href="/<%- page.get('slug') %>.html"><%- page.title() %></a></li>
     <% }); %>
  </ul>
<% }); %>
```

I've attempted to create additional templates and embed liquid, etc. within the markdown to dynamically create the navigation list. This hasn't been fruitful. Is there something I'm overlooking?

I'm looking to go down this path so that the nav pages don't have to have "hardcoded" navigation links.

I'm not super familiar with lineman, so I could be overlooking something trivial. Or, I could be looking for something that doesn't exist either.

**Comment by kytrinyx** [comment]
> Work and life get in the way sometimes.

Ah, yeah, I'm _very_ familiar with the phenomenon!

I'll see if I can figure out the page-based thing. My brain is a little bit fried right now, so I'm going to re-read this in the morning to make sure I understand what you're trying to do. I might beg @theotherzach to pair with me to figure it out. (Hi Zach!)

**Comment by johno** [comment]
No worries. And please let me know if there are any other questions I can answer to further clarify what I'm attempting to do with the navigation.

Hopefully we can get to the bottom of this. Thanks!

**Comment by kytrinyx** [comment]
I need some more context about the navigation. Would you describe the page/navigation structure that you're trying to make? Where is it that you're trying to get ahold of the categories?

**Comment by johno** [comment]
As a starting point I was hoping to get the list of links so I could filter them on a per-category basis (similar to what's happening on the index) so I can then do the following:

c4bftpgjvrq6hc7s0blehdnjqy9yqwjfnnficmunr9y

The `/languages.html` would have only the language topic links, `/contributing.html` the contributing topic links, etc.

I've attempted to get a hold of the categories in the `/pages` directory, which unsurprisingly doesn't work. I've also attempted to create a new template, `languages.us`. This is following along with the [lineman docs](http://linemanjs.com/#lineman-pages). However, it wasn't fruitful for me.

**Comment by kytrinyx** [comment]
Ok, cool, this gives me more to work with. I'll see what I can figure out.

**Comment by johno** [comment]
Great, thanks. Let me know if you encounter any other questions. Hopefully I'm just overlooking something simple! Since, I just need the following to return the pages so I can iterate over them:

``` js
category.pages.forEach(function(page) { /* ... */ }
```

I don't know why I can't seem to get it to work for the navigation pages.

**Comment by LegalizeAdulthood** [comment]
Having just submitted a pull request for lots of verbiage elaborating more details about getting started with C++, I can appreciate the ability to organize that help information in more than just one page :smile:

**Comment by kytrinyx** [comment]
I'm sorry I haven't gotten to this yet. I had some international travel, and then I got sick.

**Comment by johno** [comment]
Hey @kytrinyx ,

Has there been any movement on this? I messed around with attempting to generate the nav a bit more, but still wasn't able to have any luck. If necessary, there are a few more navigation avenues I can explore if the functionality I'm striving for isn't available. Though, it would be surprising to me since I know it's achievable with other static site generators like Jekyll.

Thanks!

**Comment by kytrinyx** [comment]
I talked to @theotherzach about pairing, and he has some availability in a couple weeks, it looks like. I simply don't have enough javascript chops to figure out how to do this, but I suspect that it's quite straight forward, and Zach has built a ton of sites on top of linemanjs, so he'll probably be able to point right at what is missing.

**Comment by johno** [comment]
Awesome!

**Comment by johno** [comment]
I've come up with a way to work around this. I should be able to update my PR to get this ready for a merge in the next few days.

**Comment by kytrinyx** [comment]
@johnotander that sounds great! I'm still waiting for Zach to get back to me after his trip to Europe.

**Comment by johno** [comment]
Quick Update: I've gotten the initial functionality working, I decided to just render a couple hidden `div`s underneath the `footer` that a sprinkle of Javascript toggles on a nav click (using a `hidden` CSS class):

``` js
$ ->
  $('.js-full-page-nav-link[data-toggle]').on('click', ->
    $('.js-full-page-nav').addClass('hidden')
    $($(this).data('toggle')).toggleClass('hidden')
  )

  $('.js-full-page-nav-close').on('click', ->
    $(this).parent().addClass('hidden')
  )
```

With each navigation being populated like so:

``` html
    <div id="nav-contributing" class="hidden full-page-nav">
      <a href="#" class="js-full-page-nav-close">Close</a>
      <% site.categories.forEach(function(category) { %>
      <% if (category.title === 'Contributing') { %>
      <div class="col-sm-6 col-sm-offset-3">
        <a class="title"><%- category.title %></a>
        <ul class="toc-section">
          <% category.pages.forEach(function(page) { %>
          <li><a href="/<%- page.get('slug') %>.html"><%- page.title() %></a></li>
          <% }); %>
        </ul>
      </div>
      <% } %>
      <% }); %>
    </div>
```

With this implementation, I can piggy back off the existing navigation, and only slightly change it's functionality (just the added `if` conditional). When a section from the header navigation is clicked, it toggles a full page nav for its sub items with a corresponding close button. I think this will be a more intuitive to navigate and it will have the appearance of a new page to the user.

I still have some more styling to iron out, but it's a few more steps in the right direction.

**Comment by kytrinyx** [comment]
Awesome!

I have a pairing session scheduled with @theotherzach this week, so we might also be able to figure out the original nav issue.

**Comment by kytrinyx** [comment]
I forgot to check back in after pairing with Zach. Basically, we were both stumped :/

**Comment by johno** [comment]
Hrm, that's too bad. I'll continue pursuing my latest implementation, then.

There's also always the possibility of switching over to Jekyll, :wink:.

**Comment by kytrinyx** [comment]
Yeah, I was actually thinking along the same lines, actually. I'm going to look at the options in Go as well. Either Ruby or Go would at least let me debug efficiently.

**Comment by kytrinyx** [comment]
I have come to the conclusion that lineman was a bad choice (in part because I simply don't know enough javascript to deal with it). I'm going to convert this to a straight-forward Sinatra app. Is there any chance of doing this in a way that could salvage the work you did?

**Comment by mfrost** [comment]
Had a hell of a time getting lineman installed. Some packages are definitely out of date. Moving to a another / a simpler foundation might be the best choice.

The merge conflict is simple: changes were made to the sidebar styles at various points in the last year. This PR deletes that file. I merged this locally and it seems to play just fine. Do note that the navigation items are not yet styled. Looks a bit like this:
nav

We can get that merged and then move forward on other styles / foundations.

**Comment by kytrinyx** [comment]
I've been moving all the language-specific documentation over to each language-specific repository, under the `docs/` repository, and serving it up from x.exercism.io, and using it in the language track pages on the main site: http://exercism.io/languages/go

The contributing documentation has gone into the contributing guide in x-common: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md

I think the right solution here is to ditch this repo entirely, and move the process-related documentation to a page ("/how-it-works" or something), and then the troubleshooting documentation to a simple "/help" page.

Let's close everything here, and write "LEGACY" in big letters in the README.

**Pull request closed without merging**
