### PR TITLE
Enhance Go help page

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
@soniakeys: I'd also like to add a section about [go lint](https://github.com/golang/lint) which I find very useful. What do you think about that?

**Comment by soniakeys** [comment]
Thank you for adding the paragraph on benchmarks.  I made my recent changes hastily and forgot to mention this.  I was probably also going to add something encouraging people to consider the effects on readability when they optimize for execution speed.  (Sometimes there are tradeoffs, but I believe there are many cases where optimization leads to more succinct and more readable code.)

I'm fine with the suggestion of go lint.  I actually thought it was in there at one point, but maybe not.

You know, one more thing I was going to add but forgot was something about how many of the functions solvers must write have an API contrived to be testable, that these functions might not always be appropriate in production code.  It's hard to word this right.  Like the objections to accumulate were that these kinds of functions are not appropriate in production code.  I would agree that the functions aren't, but the techniques inside the function certainly are.  The only way to test the code is to put it in a function.  We've skipped accumulate for now, but I ran across a number of similar cases in other exercises.

Bleh, and there's a typo and a poorly worded sentence there.  You want to amend this with lint and anything else you think it needs and then I'll fix my errors?

**Comment by sjakobi** [comment]
I have added a sentence on golint.

Regarding your concern with the difference between these exercises and production code (if I understood you correctly) - I'm pretty confident that most users are aware that many aspects that matter in production code are entirely ignored in these exercises.
It wouldn't hurt to add a paragraph on that issue of course.

**Comment by kytrinyx** [comment]
This got merged in #30

**Pull request closed without merging**
