### PR TITLE
Add page about refactoring exercises

### LINKED ISSUE #120: Add a page in support of refactoring exercises
From @pminten on the [mailing list](http://librelist.com/browser//exercism/2015/3/7/refactoring-exercises/#4cb8faf5884567301b2a2138bd91331e):

> [W]e could [...] have some kind of help page for refactoring problems 
> where we discuss how to approach refactoring and what tools can help. 
> For example if you commit every logically separate change in git with a 
> meaningful commit message then your commit log will automatically be a 
> log of the changes you did. Or one could use a tool like quilt to manage 
> a stack of patches.
> 
> A side benefit of this approach would be to encourage people to learn 
> about version control.

### PR DESCRIPTION
**Pull request by pminten**
Closes #120 

I didn't add a list of refactoring links since I don't really know which ones are good. @kytrinyx, I'm guessing you know more about this than me, can you give a few pointers?

Also I'm not entirely sure where in the hierarchy of the help section this belongs.

### CODE REVIEW

**Comment by kytrinyx** [comment]
For now "topics" is a good section. Let me think about the links thing and get back to you.

**Comment by kytrinyx** [comment]
Here are a few links that might be useful:

JB Rainsberger, on Where do I start? http://www.jbrains.ca/permalink/refactoring-where-do-i-start
The C2 Wiki on Refactoring: http://c2.com/cgi/wiki?WhatIsRefactoring
Martin Fowler's catalog of refactorings: http://refactoring.com/catalog/
The Mikado Method - https://pragprog.com/magazines/2010-06/the-mikado-method

**Comment by pminten** [comment]
Thanks. I've added them to the page.

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
