### PR TITLE
Add documentation for installing CLI using Chocolatey on Windows

### PR DESCRIPTION
**Pull request by Spinarooni**

### CODE REVIEW

**Comment by kytrinyx** [comment]
There's a conflict with another edit that went in at about the same time as yours. Would you rebase against the upstream master?

**Comment by Spinarooni** [comment]
I've made a mess of this commit wise; sorry.  I'm not very fluent with Git, although I did manage to get things merged.  It may be best to close this request and open a new one based off of a fresh fork?

**Comment by kytrinyx** [comment]
No, it's totally fine, I can pull it down and sort it out on my end :) Thank you!

**Comment by kytrinyx** [comment]
OK, I've merged it locally and pushed it up.

I wrote a little bit about my git workflow here, if you're interested: http://help.exercism.io/git-workflow.html

**Pull request closed without merging**
