### PR TITLE
Add a note to submit in the appropriate directory

### PR DESCRIPTION
**Pull request by jwood803**
I hope the language makes sense and helps make submitting a bit clearer.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Hm, so this is only true for some languages (check out scala and java, for example).

Maybe this would be a good use of the `SETUP.md` mechanism that I added a while back. Adding a file named `SETUP.md` in the root of the language track repository will cause that content to be included in the README for each problem.

**Comment by jwood803** [comment]
Ahhh, good point. I can add it to each of them.

**Comment by kytrinyx** [comment]
You're a saint. Should I close this?

**Comment by jwood803** [comment]
I got it. :]

I'll start messing with this during the weekend.

**Comment by jwood803** [comment]
Is [this](https://github.com/jwood803/xcsharp/blob/add-setup/SETUP.md) a good start for it?

**Comment by kytrinyx** [comment]
Yeah, that looks great.

**Pull request closed without merging**
