### PR TITLE
Add F# help page

### PR DESCRIPTION
**Pull request by jwood803**
This should do it! :]

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice, thank you :heart:

**Comment by jwood803** [comment]
Anytime! I'll continue to get some more exercises added, as well. Is there anything else needed?

**Comment by kytrinyx** [comment]
Nope. Not that I can tell. I'll turn this on today and give you mentorship rights on the F# track.

**Comment by jwood803** [comment]
Awesome! I'll certainly do my best with it.

**Comment by kytrinyx** [comment]
Deploying the activated track now. Let me know if there's any weirdness with it, and I'll update it tonight (or, if it's critical, ASAP).

**Comment by jwood803** [comment]
I'll mess around with it. Thanks!

**Pull request merged**
